jwt:
  header: Authorization
  expires_in: 525601 # 12 month in minutes
  mobile_expires_in: 525601 # 12 month in minutes
  secret: supersecret2025

management:
  endpoint:    
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     base-path: /management
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
    
server:
    http2:
      enabled: true
    port: 9091
    servlet:
      session:
        timeout: 600s
    undertow:
       buffer-size: 65536
       worker-threads: 800
       no-request-timeout: 600s
       threads:
         io: 2000
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 1024
    
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: account
    
    
  cloud:
    discovery:
       service-id: account
       enabled: true
    gateway:
      httpclient:
       response-timeout: 10s  
      discovery:
        locator:
          enabled: true

       
  servlet:
    multipart:
        max-file-size: 5MB
        max-request-size: 5MB
        enabled: true

  jackson:
    serialization:
      write_dates_as_timestamps: false

    
  data:
    mongodb:   
      uri: mongodb://DonDev:BC2022@mongodb:27017/accountDB?ssl=false&connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=100&maxIdleTimeMS=900000&readPreference=primaryPreferred&authSource=admin
    

eureka:
  client:
    prefer-ip-address: true
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://admin:admin@eureka:8761/eureka/
  instance:
    appname: account
    instanceId: account:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}