version: "3.3"

services:
    
  rabbitmq:    
    image: rabbitmq               
    container_name: rabbitmq
    volumes:
     - ../logs/rabbitmq/logs:/opt/rabbitmq/logs
    ports:
     - '15672:15672'
     - '5672:5672'
    networks:
     - mnet
    
  zipkinnode:
    image: openzipkin/zipkin
    container_name: zipkinnode
    environment:
      - STORAGE_TYPE=mem
    ports:
      - '9411:9411'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4096M
        reservations:
          cpus: '0.25'
          memory: 4096M
    links:  
      - rabbitmq 
    networks:
      - mnet  
    
  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb    
    volumes:
      - ~/volumes/databases/mongo/data:/data/db
      - ~/volumes/databases/mongo/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=BC2022
      - MONGO_INITDB_ROOT_USERNAME=DonDev
    command: mongod
    networks:
      mnet:
        aliases:
          - mongodb
    
  eureka:
    image: jhipster/jhipster-registry:v6.3.0
    container_name: eureka
    volumes:
      - ./central-server-config:/central-config
    environment:
      - _JAVA_OPTIONS=-Xmx1024m -Xms1024m
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=./central-config/localhost-config/ 
    ports:
      - 8761:8761

    networks:
      - mnet
      
  neo4j:
    environment:
      NEO4J_AUTH: none
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ~/volumes/databases/neo4j/:/data
    ports:
      - "7474:7474/tcp"
      - "7687:7687/tcp"
    deploy:
      replicas: 1
    networks:
     - mnet
     
  gateway:
    image: gateway
    build: ./gateway
    container_name: gateway
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:
      - account
      - friend    
    depends_on:  
      - eureka    
    ports:
      - '2022:2022'   
    networks:
      - mnet
      
  friend:
    image: friend
    env_file: .env    
    build: ./friend
    container_name: friend
    environment:
      - NEO4J_HOST_URI=${NEO4J_HOST_URI}
    links:
      - neo4j
    ports:
      - 9090:9090
    depends_on:  
      - eureka
      - neo4j
      - mongodb
    deploy:
      replicas: 1
    networks:
     - mnet
     
  account:
    image: account     
    build: ./account
    container_name: account
    env_file: 
      - .env
    environment:
      - NEO4J_HOST_URI:${NEO4J_HOST_URI}
    links:
      - mongodb
    ports:
      - 9091:9091 
    depends_on:  
      - eureka
      - neo4j
      - mongodb
    deploy:
      replicas: 1
    networks:
     - mnet
     
  producer:
    image: producer
    build: ./producer
    container_name: producer
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:
      - mongodb     
    depends_on:      
      - mongodb       
    ports:
      - '9092:9092'
    volumes:
      - /opt/producer/logs/:/opt/producer/logs
    networks:
      - mnet
      
      
  chat:    
   image: chat 
   build: ./chat                
   container_name: chat
   links:
      - gateway
   environment:
    - JVM_OPTS=-Xmx4g -Xms1g -XX:MaxPermSize=2g
    - CATALINA_OPTS=-Xmx4g -Xms1g -XX:MaxPermSize=2g
   volumes:
    - ../data/micro/realtime/logs/:/opt/realtime/logs
   ports:
    - '9000:9000'
   networks:
    - mnet 
     
networks:
  mnet:
    driver: bridge
