management:
  endpoint:    
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     base-path: /management
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'


db_url: ${NEO4J_HOST_URI:localhost}

spring:
    
  main:
    allow-bean-definition-overriding: true
  application:
    name: friend
    
    
  cloud:
    discovery:
       service-id: friend
       enabled: true
       
       
  zipkin:
    baseUrl: http://zipkinnode:9411
    enabled: true
  sleuth:
    enabled: true
    http:
      enabled: true   
    sampler:
    percentage: 1
       
  servlet:
    multipart:
        max-file-size: 5MB
        max-request-size: 5MB
        enabled: true

  jackson:
    serialization:
      write_dates_as_timestamps: false

  data:
    neo4j:
       uri: bolt://${db_url:localhost}:7687
      
server:
    http2:
      enabled: true
    port: 9090
    servlet:
      session:
        timeout: 600s
    undertow:
       buffer-size: 65536
       worker-threads: 800
       no-request-timeout: 600s
       threads:
         io: 2000
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 1024

eureka:
  client:
    prefer-ip-address: true
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://admin:admin@eureka:8761/eureka/
  instance:
    appname: friend
    instanceId: friend:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}